angora_build_task:
    container:
        image: rust:latest
    cargo_cache:
        folder: $CARGO_HOME/registry
        #    fingerprint_script: cat Cargo.lock
    build_script: 
        - apt-get update
        - apt-get install -y cmake python
        - cmake --version
        - ./build/build.sh
    test_script: cargo test
    before_cache_script: rm -rf $CARGO_HOME/registry/index
