#
# Modified from AFL llvm mode.
# -----------------------------------------
#
# Written by Laszlo Szekeres <lszekeres@google.com> and
#            Michal Zalewski <lcamtuf@google.com>
#
# LLVM integration design comes from Laszlo Szekeres.
#
# Copyright 2015, 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#

PREFIX      ?= ../bin/

LLVM_CONFIG ?= llvm-config

ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

CFLAGS      ?= -O3 -funroll-loops -g
CFLAGS      += -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign 

CXXFLAGS    ?= -O3 -funroll-loops -g
CXXFLAGS    += -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign \
               -Wno-variadic-macros

CLANG_CFL    = `$(LLVM_CONFIG) --cxxflags` -fno-rtti -fpic $(CXXFLAGS)
CLANG_LFL    = `$(LLVM_CONFIG) --ldflags` $(LDFLAGS)

# User teor2345 reports that this is required to make things work on MacOS X.

ifeq "$(shell uname)" "Darwin"
  CLANG_LFL += -Wl,-flat_namespace -Wl,-undefined,suppress
endif

LLVM_VERSION_MAJOR=`${LLVM_CONFIG} --version | cut -f1 -d.`
LLVM_VERSION_MINOR=`${LLVM_CONFIG} --version | cut -f2 -d.`
VALID_LLVM_VERSION=$(shell expr ${LLVM_VERSION_MAJOR} \>= 4 \& ${LLVM_VERSION_MAJOR} \<= 7)

test_deps:
	if [ ! -d ${PREFIX} ]; then mkdir -p ${PREFIX}; fi;
	@echo "[*] Checking for working 'llvm-config'..."

	@which $(LLVM_CONFIG) >/dev/null 2>&1 || ( echo "[-] Oops, can't find 'llvm-config'. Install clang or set \$$LLVM_CONFIG or \$$PATH beforehand."; echo "    (Sometimes, the binary will be named llvm-config-4 or something like that.)"; exit 1 )
	@echo "#define LLVM_VERSION_MAJOR ${LLVM_VERSION_MAJOR}" > ${ROOT_DIR}/version.config
	@echo "#define LLVM_VERSION_MINOR ${LLVM_VERSION_MINOR}" >> ${ROOT_DIR}/version.config

ifeq "$(VALID_LLVM_VERSION)" "0"
	@echo "[-] LLVM version is `${LLVM_CONFIG} --version`, please use LLVM 4.0.0 - 7.1.0"
	@exit 1
endif

	@echo "[*] Checking for working '$(CC)'..."
	@which $(CC) >/dev/null 2>&1 || ( echo "[-] Oops, can't find '$(CC)'. Make sure that it's in your \$$PATH (or set \$$CC and \$$CXX)."; exit 1 )
	@echo "[+] All set and ready to build."

